### ISSUE TITLE
Tabellen er feilsortert på diverse enheter

### ISSUE THREAD

**Issue by torkjels** [Ancvik/react-fotball#2]
Som vi har sett sorteres tabellen feil på f.eks. Kristian sin telefon.
Plass-nummer og opprykks-/nedrykksfarge (som baseres på `team.place`) er riktig, og jeg ser at det påsees at lagene faktisk er sortert på `team.place` før man gjør noe annet.

Knut foreslo at dette kanskje kommer av at du mangler `key` på tabellradene dine. Du får muligens en advarsel om det i konsollen.
https://reactjs.org/docs/lists-and-keys.html#keys

**Comment by ghost** [comment]
@Ancvik skulle egentlig tagge 0907f397d4a646a54144510cb83f7119e323dd54 på denne issuen.

**Comment by Ancvik** [comment]
fikset sorteringen fra position til place. virker som at det ble mixup ved at position var undefined som fucket opp tabellen på noen enheter
